### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by andrii-trush** [nvima/chat-ui#2]
Hello. Thank you for awesome package. 

Is there any opportunity to make infinite scroll with lazy loading of content, to prevent loading of all conversation during init?

**Comment by nvima** [comment]
I'm sorry, I don't plan to work on the ChatUI any further. With this project I wanted to test what you can do with https://github.com/BuilderIO/mitosis. I had a lot of problems getting it to work with more frameworks and then lost the desire to add more features.
